version: '3.8'

services:
  wa-checker-bot:
    build: .
    container_name: wa-checker-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./auth_info_baileys:/app/auth_info_baileys
    stdin_open: true
    tty: true
